// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pizdagladki/full/services/koth/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockRankService is a mock of RankService interface.
type MockRankService struct {
	ctrl     *gomock.Controller
	recorder *MockRankServiceMockRecorder
	isgomock struct{}
}

// MockRankServiceMockRecorder is the mock recorder for MockRankService.
type MockRankServiceMockRecorder struct {
	mock *MockRankService
}

// NewMockRankService creates a new mock instance.
func NewMockRankService(ctrl *gomock.Controller) *MockRankService {
	mock := &MockRankService{ctrl: ctrl}
	mock.recorder = &MockRankServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankService) EXPECT() *MockRankServiceMockRecorder {
	return m.recorder
}

// Leaderboard mocks base method.
func (m *MockRankService) Leaderboard(ctx context.Context) ([]domain.RankCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leaderboard", ctx)
	ret0, _ := ret[0].([]domain.RankCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leaderboard indicates an expected call of Leaderboard.
func (mr *MockRankServiceMockRecorder) Leaderboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leaderboard", reflect.TypeOf((*MockRankService)(nil).Leaderboard), ctx)
}

// Me mocks base method.
func (m *MockRankService) Me(ctx context.Context, userID int64) (domain.MeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx, userID)
	ret0, _ := ret[0].(domain.MeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockRankServiceMockRecorder) Me(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockRankService)(nil).Me), ctx, userID)
}

// SubmitAttempt mocks base method.
func (m *MockRankService) SubmitAttempt(ctx context.Context, userID int64, heldMs int) (domain.AttemptResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitAttempt", ctx, userID, heldMs)
	ret0, _ := ret[0].(domain.AttemptResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitAttempt indicates an expected call of SubmitAttempt.
func (mr *MockRankServiceMockRecorder) SubmitAttempt(ctx, userID, heldMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitAttempt", reflect.TypeOf((*MockRankService)(nil).SubmitAttempt), ctx, userID, heldMs)
}

// MockHillService is a mock of HillService interface.
type MockHillService struct {
	ctrl     *gomock.Controller
	recorder *MockHillServiceMockRecorder
	isgomock struct{}
}

// MockHillServiceMockRecorder is the mock recorder for MockHillService.
type MockHillServiceMockRecorder struct {
	mock *MockHillService
}

// NewMockHillService creates a new mock instance.
func NewMockHillService(ctrl *gomock.Controller) *MockHillService {
	mock := &MockHillService{ctrl: ctrl}
	mock.recorder = &MockHillServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHillService) EXPECT() *MockHillServiceMockRecorder {
	return m.recorder
}

// Challenge mocks base method.
func (m *MockHillService) Challenge(ctx context.Context, hillType string, userID int64, survivedMs int, newClipID string) (domain.ChallengeOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Challenge", ctx, hillType, userID, survivedMs, newClipID)
	ret0, _ := ret[0].(domain.ChallengeOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Challenge indicates an expected call of Challenge.
func (mr *MockHillServiceMockRecorder) Challenge(ctx, hillType, userID, survivedMs, newClipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Challenge", reflect.TypeOf((*MockHillService)(nil).Challenge), ctx, hillType, userID, survivedMs, newClipID)
}

// CurrentKing mocks base method.
func (m *MockHillService) CurrentKing(ctx context.Context, hillType string) (domain.KingReign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentKing", ctx, hillType)
	ret0, _ := ret[0].(domain.KingReign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentKing indicates an expected call of CurrentKing.
func (mr *MockHillServiceMockRecorder) CurrentKing(ctx, hillType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentKing", reflect.TypeOf((*MockHillService)(nil).CurrentKing), ctx, hillType)
}

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// ResolveSession mocks base method.
func (m *MockSessionService) ResolveSession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSession indicates an expected call of ResolveSession.
func (mr *MockSessionServiceMockRecorder) ResolveSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSession", reflect.TypeOf((*MockSessionService)(nil).ResolveSession), ctx, sessionID)
}
