// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/ratings/internal/api/domain"
	service "github.com/pizdagladki/full/services/ratings/internal/api/service"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingsService is a mock of RatingsService interface.
type MockRatingsService struct {
	ctrl     *gomock.Controller
	recorder *MockRatingsServiceMockRecorder
	isgomock struct{}
}

// MockRatingsServiceMockRecorder is the mock recorder for MockRatingsService.
type MockRatingsServiceMockRecorder struct {
	mock *MockRatingsService
}

// NewMockRatingsService creates a new mock instance.
func NewMockRatingsService(ctrl *gomock.Controller) *MockRatingsService {
	mock := &MockRatingsService{ctrl: ctrl}
	mock.recorder = &MockRatingsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingsService) EXPECT() *MockRatingsServiceMockRecorder {
	return m.recorder
}

// ApplyMatchResult mocks base method.
func (m *MockRatingsService) ApplyMatchResult(ctx context.Context, input domain.MatchInput) (domain.MatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyMatchResult", ctx, input)
	ret0, _ := ret[0].(domain.MatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyMatchResult indicates an expected call of ApplyMatchResult.
func (mr *MockRatingsServiceMockRecorder) ApplyMatchResult(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMatchResult", reflect.TypeOf((*MockRatingsService)(nil).ApplyMatchResult), ctx, input)
}

// GetRating mocks base method.
func (m *MockRatingsService) GetRating(ctx context.Context, userID int64) (domain.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRating", ctx, userID)
	ret0, _ := ret[0].(domain.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRating indicates an expected call of GetRating.
func (mr *MockRatingsServiceMockRecorder) GetRating(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRating", reflect.TypeOf((*MockRatingsService)(nil).GetRating), ctx, userID)
}

// ListMatchHistory mocks base method.
func (m *MockRatingsService) ListMatchHistory(ctx context.Context, userID int64, limit, offset int) ([]domain.MatchHistoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatchHistory", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.MatchHistoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatchHistory indicates an expected call of ListMatchHistory.
func (mr *MockRatingsServiceMockRecorder) ListMatchHistory(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatchHistory", reflect.TypeOf((*MockRatingsService)(nil).ListMatchHistory), ctx, userID, limit, offset)
}

// MockPointsClient is a mock of PointsClient interface.
type MockPointsClient struct {
	ctrl     *gomock.Controller
	recorder *MockPointsClientMockRecorder
	isgomock struct{}
}

// MockPointsClientMockRecorder is the mock recorder for MockPointsClient.
type MockPointsClientMockRecorder struct {
	mock *MockPointsClient
}

// NewMockPointsClient creates a new mock instance.
func NewMockPointsClient(ctrl *gomock.Controller) *MockPointsClient {
	mock := &MockPointsClient{ctrl: ctrl}
	mock.recorder = &MockPointsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPointsClient) EXPECT() *MockPointsClientMockRecorder {
	return m.recorder
}

// Credit mocks base method.
func (m *MockPointsClient) Credit(ctx context.Context, req service.CreditRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credit", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Credit indicates an expected call of Credit.
func (mr *MockPointsClientMockRecorder) Credit(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credit", reflect.TypeOf((*MockPointsClient)(nil).Credit), ctx, req)
}
