// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pizdagladki/full/services/koth/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRankRepository is a mock of RankRepository interface.
type MockRankRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRankRepositoryMockRecorder
	isgomock struct{}
}

// MockRankRepositoryMockRecorder is the mock recorder for MockRankRepository.
type MockRankRepositoryMockRecorder struct {
	mock *MockRankRepository
}

// NewMockRankRepository creates a new mock instance.
func NewMockRankRepository(ctrl *gomock.Controller) *MockRankRepository {
	mock := &MockRankRepository{ctrl: ctrl}
	mock.recorder = &MockRankRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankRepository) EXPECT() *MockRankRepositoryMockRecorder {
	return m.recorder
}

// GetRank mocks base method.
func (m *MockRankRepository) GetRank(ctx context.Context, userID int64, day time.Time) (*domain.HillRank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRank", ctx, userID, day)
	ret0, _ := ret[0].(*domain.HillRank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRank indicates an expected call of GetRank.
func (mr *MockRankRepositoryMockRecorder) GetRank(ctx, userID, day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRank", reflect.TypeOf((*MockRankRepository)(nil).GetRank), ctx, userID, day)
}

// RankDistribution mocks base method.
func (m *MockRankRepository) RankDistribution(ctx context.Context, day time.Time) ([]domain.RankCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankDistribution", ctx, day)
	ret0, _ := ret[0].([]domain.RankCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankDistribution indicates an expected call of RankDistribution.
func (mr *MockRankRepositoryMockRecorder) RankDistribution(ctx, day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankDistribution", reflect.TypeOf((*MockRankRepository)(nil).RankDistribution), ctx, day)
}

// UpsertRank mocks base method.
func (m *MockRankRepository) UpsertRank(ctx context.Context, userID int64, day time.Time, newRank, bestHoldMs int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRank", ctx, userID, day, newRank, bestHoldMs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRank indicates an expected call of UpsertRank.
func (mr *MockRankRepositoryMockRecorder) UpsertRank(ctx, userID, day, newRank, bestHoldMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRank", reflect.TypeOf((*MockRankRepository)(nil).UpsertRank), ctx, userID, day, newRank, bestHoldMs)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// UserIDBySession mocks base method.
func (m *MockSessionRepository) UserIDBySession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDBySession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIDBySession indicates an expected call of UserIDBySession.
func (mr *MockSessionRepositoryMockRecorder) UserIDBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDBySession", reflect.TypeOf((*MockSessionRepository)(nil).UserIDBySession), ctx, sessionID)
}
