// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/ratings/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRatingsRepository is a mock of RatingsRepository interface.
type MockRatingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRatingsRepositoryMockRecorder
	isgomock struct{}
}

// MockRatingsRepositoryMockRecorder is the mock recorder for MockRatingsRepository.
type MockRatingsRepositoryMockRecorder struct {
	mock *MockRatingsRepository
}

// NewMockRatingsRepository creates a new mock instance.
func NewMockRatingsRepository(ctrl *gomock.Controller) *MockRatingsRepository {
	mock := &MockRatingsRepository{ctrl: ctrl}
	mock.recorder = &MockRatingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingsRepository) EXPECT() *MockRatingsRepositoryMockRecorder {
	return m.recorder
}

// ApplyMatchResult mocks base method.
func (m *MockRatingsRepository) ApplyMatchResult(ctx context.Context, input domain.MatchInput) (domain.MatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyMatchResult", ctx, input)
	ret0, _ := ret[0].(domain.MatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyMatchResult indicates an expected call of ApplyMatchResult.
func (mr *MockRatingsRepositoryMockRecorder) ApplyMatchResult(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMatchResult", reflect.TypeOf((*MockRatingsRepository)(nil).ApplyMatchResult), ctx, input)
}

// GetRating mocks base method.
func (m *MockRatingsRepository) GetRating(ctx context.Context, userID int64) (domain.Rating, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRating", ctx, userID)
	ret0, _ := ret[0].(domain.Rating)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRating indicates an expected call of GetRating.
func (mr *MockRatingsRepositoryMockRecorder) GetRating(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRating", reflect.TypeOf((*MockRatingsRepository)(nil).GetRating), ctx, userID)
}

// ListMatchHistory mocks base method.
func (m *MockRatingsRepository) ListMatchHistory(ctx context.Context, userID int64, limit, offset int) ([]domain.MatchHistoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatchHistory", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.MatchHistoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatchHistory indicates an expected call of ListMatchHistory.
func (mr *MockRatingsRepositoryMockRecorder) ListMatchHistory(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatchHistory", reflect.TypeOf((*MockRatingsRepository)(nil).ListMatchHistory), ctx, userID, limit, offset)
}
