// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/store/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentProvider is a mock of PaymentProvider interface.
type MockPaymentProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentProviderMockRecorder
	isgomock struct{}
}

// MockPaymentProviderMockRecorder is the mock recorder for MockPaymentProvider.
type MockPaymentProviderMockRecorder struct {
	mock *MockPaymentProvider
}

// NewMockPaymentProvider creates a new mock instance.
func NewMockPaymentProvider(ctrl *gomock.Controller) *MockPaymentProvider {
	mock := &MockPaymentProvider{ctrl: ctrl}
	mock.recorder = &MockPaymentProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentProvider) EXPECT() *MockPaymentProviderMockRecorder {
	return m.recorder
}

// CreatePaymentIntent mocks base method.
func (m *MockPaymentProvider) CreatePaymentIntent(ctx context.Context, productID int64, amountCents int) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePaymentIntent", ctx, productID, amountCents)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreatePaymentIntent indicates an expected call of CreatePaymentIntent.
func (mr *MockPaymentProviderMockRecorder) CreatePaymentIntent(ctx, productID, amountCents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePaymentIntent", reflect.TypeOf((*MockPaymentProvider)(nil).CreatePaymentIntent), ctx, productID, amountCents)
}

// VerifyWebhook mocks base method.
func (m *MockPaymentProvider) VerifyWebhook(payload []byte, sigHeader string) (string, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhook", payload, sigHeader)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// VerifyWebhook indicates an expected call of VerifyWebhook.
func (mr *MockPaymentProviderMockRecorder) VerifyWebhook(payload, sigHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhook", reflect.TypeOf((*MockPaymentProvider)(nil).VerifyWebhook), payload, sigHeader)
}

// MockPurchaseService is a mock of PurchaseService interface.
type MockPurchaseService struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseServiceMockRecorder
	isgomock struct{}
}

// MockPurchaseServiceMockRecorder is the mock recorder for MockPurchaseService.
type MockPurchaseServiceMockRecorder struct {
	mock *MockPurchaseService
}

// NewMockPurchaseService creates a new mock instance.
func NewMockPurchaseService(ctrl *gomock.Controller) *MockPurchaseService {
	mock := &MockPurchaseService{ctrl: ctrl}
	mock.recorder = &MockPurchaseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseService) EXPECT() *MockPurchaseServiceMockRecorder {
	return m.recorder
}

// HandleWebhook mocks base method.
func (m *MockPurchaseService) HandleWebhook(ctx context.Context, payload []byte, sigHeader string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebhook", ctx, payload, sigHeader)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebhook indicates an expected call of HandleWebhook.
func (mr *MockPurchaseServiceMockRecorder) HandleWebhook(ctx, payload, sigHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhook", reflect.TypeOf((*MockPurchaseService)(nil).HandleWebhook), ctx, payload, sigHeader)
}

// InitiatePurchase mocks base method.
func (m *MockPurchaseService) InitiatePurchase(ctx context.Context, userID, productID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitiatePurchase", ctx, userID, productID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitiatePurchase indicates an expected call of InitiatePurchase.
func (mr *MockPurchaseServiceMockRecorder) InitiatePurchase(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitiatePurchase", reflect.TypeOf((*MockPurchaseService)(nil).InitiatePurchase), ctx, userID, productID)
}

// MockCatalogService is a mock of CatalogService interface.
type MockCatalogService struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogServiceMockRecorder
	isgomock struct{}
}

// MockCatalogServiceMockRecorder is the mock recorder for MockCatalogService.
type MockCatalogServiceMockRecorder struct {
	mock *MockCatalogService
}

// NewMockCatalogService creates a new mock instance.
func NewMockCatalogService(ctrl *gomock.Controller) *MockCatalogService {
	mock := &MockCatalogService{ctrl: ctrl}
	mock.recorder = &MockCatalogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogService) EXPECT() *MockCatalogServiceMockRecorder {
	return m.recorder
}

// ListCatalog mocks base method.
func (m *MockCatalogService) ListCatalog(ctx context.Context, kind *string) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCatalog", ctx, kind)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCatalog indicates an expected call of ListCatalog.
func (mr *MockCatalogServiceMockRecorder) ListCatalog(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCatalog", reflect.TypeOf((*MockCatalogService)(nil).ListCatalog), ctx, kind)
}

// MockInventoryService is a mock of InventoryService interface.
type MockInventoryService struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryServiceMockRecorder
	isgomock struct{}
}

// MockInventoryServiceMockRecorder is the mock recorder for MockInventoryService.
type MockInventoryServiceMockRecorder struct {
	mock *MockInventoryService
}

// NewMockInventoryService creates a new mock instance.
func NewMockInventoryService(ctrl *gomock.Controller) *MockInventoryService {
	mock := &MockInventoryService{ctrl: ctrl}
	mock.recorder = &MockInventoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryService) EXPECT() *MockInventoryServiceMockRecorder {
	return m.recorder
}

// ListInventory mocks base method.
func (m *MockInventoryService) ListInventory(ctx context.Context, userID int64) ([]domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventory", ctx, userID)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventory indicates an expected call of ListInventory.
func (mr *MockInventoryServiceMockRecorder) ListInventory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventory", reflect.TypeOf((*MockInventoryService)(nil).ListInventory), ctx, userID)
}

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// ResolveSession mocks base method.
func (m *MockSessionService) ResolveSession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSession indicates an expected call of ResolveSession.
func (mr *MockSessionServiceMockRecorder) ResolveSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSession", reflect.TypeOf((*MockSessionService)(nil).ResolveSession), ctx, sessionID)
}
