// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	domain "github.com/pizdagladki/full/services/media/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockObjectStore is a mock of ObjectStore interface.
type MockObjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreMockRecorder
	isgomock struct{}
}

// MockObjectStoreMockRecorder is the mock recorder for MockObjectStore.
type MockObjectStoreMockRecorder struct {
	mock *MockObjectStore
}

// NewMockObjectStore creates a new mock instance.
func NewMockObjectStore(ctrl *gomock.Controller) *MockObjectStore {
	mock := &MockObjectStore{ctrl: ctrl}
	mock.recorder = &MockObjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStore) EXPECT() *MockObjectStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockObjectStore) Get(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObjectStoreMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectStore)(nil).Get), ctx, key)
}

// PresignedGetURL mocks base method.
func (m *MockObjectStore) PresignedGetURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignedGetURL", ctx, key, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignedGetURL indicates an expected call of PresignedGetURL.
func (mr *MockObjectStoreMockRecorder) PresignedGetURL(ctx, key, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignedGetURL", reflect.TypeOf((*MockObjectStore)(nil).PresignedGetURL), ctx, key, ttl)
}

// Put mocks base method.
func (m *MockObjectStore) Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, r, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockObjectStoreMockRecorder) Put(ctx, key, r, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockObjectStore)(nil).Put), ctx, key, r, size, contentType)
}

// Remove mocks base method.
func (m *MockObjectStore) Remove(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockObjectStoreMockRecorder) Remove(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockObjectStore)(nil).Remove), ctx, key)
}

// MockFFmpegRunner is a mock of FFmpegRunner interface.
type MockFFmpegRunner struct {
	ctrl     *gomock.Controller
	recorder *MockFFmpegRunnerMockRecorder
	isgomock struct{}
}

// MockFFmpegRunnerMockRecorder is the mock recorder for MockFFmpegRunner.
type MockFFmpegRunnerMockRecorder struct {
	mock *MockFFmpegRunner
}

// NewMockFFmpegRunner creates a new mock instance.
func NewMockFFmpegRunner(ctrl *gomock.Controller) *MockFFmpegRunner {
	mock := &MockFFmpegRunner{ctrl: ctrl}
	mock.recorder = &MockFFmpegRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFFmpegRunner) EXPECT() *MockFFmpegRunnerMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockFFmpegRunner) Convert(ctx context.Context, inputPath, outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", ctx, inputPath, outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Convert indicates an expected call of Convert.
func (mr *MockFFmpegRunnerMockRecorder) Convert(ctx, inputPath, outputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockFFmpegRunner)(nil).Convert), ctx, inputPath, outputPath)
}

// MockClipService is a mock of ClipService interface.
type MockClipService struct {
	ctrl     *gomock.Controller
	recorder *MockClipServiceMockRecorder
	isgomock struct{}
}

// MockClipServiceMockRecorder is the mock recorder for MockClipService.
type MockClipServiceMockRecorder struct {
	mock *MockClipService
}

// NewMockClipService creates a new mock instance.
func NewMockClipService(ctrl *gomock.Controller) *MockClipService {
	mock := &MockClipService{ctrl: ctrl}
	mock.recorder = &MockClipServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipService) EXPECT() *MockClipServiceMockRecorder {
	return m.recorder
}

// DownloadURL mocks base method.
func (m *MockClipService) DownloadURL(ctx context.Context, userID, clipID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadURL", ctx, userID, clipID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadURL indicates an expected call of DownloadURL.
func (mr *MockClipServiceMockRecorder) DownloadURL(ctx, userID, clipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadURL", reflect.TypeOf((*MockClipService)(nil).DownloadURL), ctx, userID, clipID)
}

// GetMP4URL mocks base method.
func (m *MockClipService) GetMP4URL(ctx context.Context, userID, clipID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMP4URL", ctx, userID, clipID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMP4URL indicates an expected call of GetMP4URL.
func (mr *MockClipServiceMockRecorder) GetMP4URL(ctx, userID, clipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMP4URL", reflect.TypeOf((*MockClipService)(nil).GetMP4URL), ctx, userID, clipID)
}

// List mocks base method.
func (m *MockClipService) List(ctx context.Context, userID int64) ([]domain.Clip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID)
	ret0, _ := ret[0].([]domain.Clip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClipServiceMockRecorder) List(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClipService)(nil).List), ctx, userID)
}

// RequestConvert mocks base method.
func (m *MockClipService) RequestConvert(ctx context.Context, userID, clipID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestConvert", ctx, userID, clipID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestConvert indicates an expected call of RequestConvert.
func (mr *MockClipServiceMockRecorder) RequestConvert(ctx, userID, clipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestConvert", reflect.TypeOf((*MockClipService)(nil).RequestConvert), ctx, userID, clipID)
}

// Upload mocks base method.
func (m *MockClipService) Upload(ctx context.Context, userID int64, contentType string, size int64, r io.Reader) (domain.Clip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, userID, contentType, size, r)
	ret0, _ := ret[0].(domain.Clip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockClipServiceMockRecorder) Upload(ctx, userID, contentType, size, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockClipService)(nil).Upload), ctx, userID, contentType, size, r)
}

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// ResolveSession mocks base method.
func (m *MockSessionService) ResolveSession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSession indicates an expected call of ResolveSession.
func (mr *MockSessionServiceMockRecorder) ResolveSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSession", reflect.TypeOf((*MockSessionService)(nil).ResolveSession), ctx, sessionID)
}

// MockKingClipService is a mock of KingClipService interface.
type MockKingClipService struct {
	ctrl     *gomock.Controller
	recorder *MockKingClipServiceMockRecorder
	isgomock struct{}
}

// MockKingClipServiceMockRecorder is the mock recorder for MockKingClipService.
type MockKingClipServiceMockRecorder struct {
	mock *MockKingClipService
}

// NewMockKingClipService creates a new mock instance.
func NewMockKingClipService(ctrl *gomock.Controller) *MockKingClipService {
	mock := &MockKingClipService{ctrl: ctrl}
	mock.recorder = &MockKingClipServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKingClipService) EXPECT() *MockKingClipServiceMockRecorder {
	return m.recorder
}

// CurrentURL mocks base method.
func (m *MockKingClipService) CurrentURL(ctx context.Context, hillType string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentURL", ctx, hillType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CurrentURL indicates an expected call of CurrentURL.
func (mr *MockKingClipServiceMockRecorder) CurrentURL(ctx, hillType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentURL", reflect.TypeOf((*MockKingClipService)(nil).CurrentURL), ctx, hillType)
}

// Delete mocks base method.
func (m *MockKingClipService) Delete(ctx context.Context, userID, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKingClipServiceMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKingClipService)(nil).Delete), ctx, userID, id)
}

// ExpireByID mocks base method.
func (m *MockKingClipService) ExpireByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireByID indicates an expected call of ExpireByID.
func (mr *MockKingClipServiceMockRecorder) ExpireByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireByID", reflect.TypeOf((*MockKingClipService)(nil).ExpireByID), ctx, id)
}

// Upload mocks base method.
func (m *MockKingClipService) Upload(ctx context.Context, userID int64, hillType string, blinkTsMs int64, contentType string, size int64, r io.Reader) (domain.KingClip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, userID, hillType, blinkTsMs, contentType, size, r)
	ret0, _ := ret[0].(domain.KingClip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockKingClipServiceMockRecorder) Upload(ctx, userID, hillType, blinkTsMs, contentType, size, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockKingClipService)(nil).Upload), ctx, userID, hillType, blinkTsMs, contentType, size, r)
}
