// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/pizdagladki/full/services/signaling/internal/api/service"
	gomock "go.uber.org/mock/gomock"
)

// MockConn is a mock of Conn interface.
type MockConn struct {
	ctrl     *gomock.Controller
	recorder *MockConnMockRecorder
	isgomock struct{}
}

// MockConnMockRecorder is the mock recorder for MockConn.
type MockConnMockRecorder struct {
	mock *MockConn
}

// NewMockConn creates a new mock instance.
func NewMockConn(ctrl *gomock.Controller) *MockConn {
	mock := &MockConn{ctrl: ctrl}
	mock.recorder = &MockConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConn) EXPECT() *MockConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConn) Close(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", reason)
}

// Close indicates an expected call of Close.
func (mr *MockConnMockRecorder) Close(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConn)(nil).Close), reason)
}

// Send mocks base method.
func (m *MockConn) Send(raw []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", raw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockConnMockRecorder) Send(raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockConn)(nil).Send), raw)
}

// UserID mocks base method.
func (m *MockConn) UserID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockConnMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockConn)(nil).UserID))
}

// MockSignalingService is a mock of SignalingService interface.
type MockSignalingService struct {
	ctrl     *gomock.Controller
	recorder *MockSignalingServiceMockRecorder
	isgomock struct{}
}

// MockSignalingServiceMockRecorder is the mock recorder for MockSignalingService.
type MockSignalingServiceMockRecorder struct {
	mock *MockSignalingService
}

// NewMockSignalingService creates a new mock instance.
func NewMockSignalingService(ctrl *gomock.Controller) *MockSignalingService {
	mock := &MockSignalingService{ctrl: ctrl}
	mock.recorder = &MockSignalingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignalingService) EXPECT() *MockSignalingServiceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockSignalingService) CreateRoom(ctx context.Context, conn service.Conn) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, conn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockSignalingServiceMockRecorder) CreateRoom(ctx, conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockSignalingService)(nil).CreateRoom), ctx, conn)
}

// Join mocks base method.
func (m *MockSignalingService) Join(ctx context.Context, conn service.Conn, roomID, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, conn, roomID, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockSignalingServiceMockRecorder) Join(ctx, conn, roomID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockSignalingService)(nil).Join), ctx, conn, roomID, mode)
}

// JoinByCode mocks base method.
func (m *MockSignalingService) JoinByCode(ctx context.Context, conn service.Conn, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinByCode", ctx, conn, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JoinByCode indicates an expected call of JoinByCode.
func (mr *MockSignalingServiceMockRecorder) JoinByCode(ctx, conn, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinByCode", reflect.TypeOf((*MockSignalingService)(nil).JoinByCode), ctx, conn, code)
}

// Leave mocks base method.
func (m *MockSignalingService) Leave(ctx context.Context, conn service.Conn, roomID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Leave", ctx, conn, roomID)
}

// Leave indicates an expected call of Leave.
func (mr *MockSignalingServiceMockRecorder) Leave(ctx, conn, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockSignalingService)(nil).Leave), ctx, conn, roomID)
}

// Relay mocks base method.
func (m *MockSignalingService) Relay(ctx context.Context, conn service.Conn, roomID string, raw []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Relay", ctx, conn, roomID, raw)
	ret0, _ := ret[0].(error)
	return ret0
}

// Relay indicates an expected call of Relay.
func (mr *MockSignalingServiceMockRecorder) Relay(ctx, conn, roomID, raw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Relay", reflect.TypeOf((*MockSignalingService)(nil).Relay), ctx, conn, roomID, raw)
}

// ReportEvent mocks base method.
func (m *MockSignalingService) ReportEvent(ctx context.Context, conn service.Conn, roomID, eventType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportEvent", ctx, conn, roomID, eventType)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportEvent indicates an expected call of ReportEvent.
func (mr *MockSignalingServiceMockRecorder) ReportEvent(ctx, conn, roomID, eventType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportEvent", reflect.TypeOf((*MockSignalingService)(nil).ReportEvent), ctx, conn, roomID, eventType)
}

// MockRatingsClient is a mock of RatingsClient interface.
type MockRatingsClient struct {
	ctrl     *gomock.Controller
	recorder *MockRatingsClientMockRecorder
	isgomock struct{}
}

// MockRatingsClientMockRecorder is the mock recorder for MockRatingsClient.
type MockRatingsClientMockRecorder struct {
	mock *MockRatingsClient
}

// NewMockRatingsClient creates a new mock instance.
func NewMockRatingsClient(ctrl *gomock.Controller) *MockRatingsClient {
	mock := &MockRatingsClient{ctrl: ctrl}
	mock.recorder = &MockRatingsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRatingsClient) EXPECT() *MockRatingsClientMockRecorder {
	return m.recorder
}

// ApplyResult mocks base method.
func (m *MockRatingsClient) ApplyResult(ctx context.Context, req service.ApplyResultRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyResult", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyResult indicates an expected call of ApplyResult.
func (mr *MockRatingsClientMockRecorder) ApplyResult(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyResult", reflect.TypeOf((*MockRatingsClient)(nil).ApplyResult), ctx, req)
}
