// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pizdagladki/full/services/matchmaking/internal/api/domain"
	service "github.com/pizdagladki/full/services/matchmaking/internal/api/service"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchmakingService is a mock of MatchmakingService interface.
type MockMatchmakingService struct {
	ctrl     *gomock.Controller
	recorder *MockMatchmakingServiceMockRecorder
	isgomock struct{}
}

// MockMatchmakingServiceMockRecorder is the mock recorder for MockMatchmakingService.
type MockMatchmakingServiceMockRecorder struct {
	mock *MockMatchmakingService
}

// NewMockMatchmakingService creates a new mock instance.
func NewMockMatchmakingService(ctrl *gomock.Controller) *MockMatchmakingService {
	mock := &MockMatchmakingService{ctrl: ctrl}
	mock.recorder = &MockMatchmakingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchmakingService) EXPECT() *MockMatchmakingServiceMockRecorder {
	return m.recorder
}

// Join mocks base method.
func (m *MockMatchmakingService) Join(ctx context.Context, conn service.Conn, player domain.Player) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, conn, player)
	ret0, _ := ret[0].(error)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockMatchmakingServiceMockRecorder) Join(ctx, conn, player any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockMatchmakingService)(nil).Join), ctx, conn, player)
}

// Leave mocks base method.
func (m *MockMatchmakingService) Leave(ctx context.Context, userID int64, mode string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Leave", ctx, userID, mode)
}

// Leave indicates an expected call of Leave.
func (mr *MockMatchmakingServiceMockRecorder) Leave(ctx, userID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockMatchmakingService)(nil).Leave), ctx, userID, mode)
}

// Tick mocks base method.
func (m *MockMatchmakingService) Tick(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Tick", ctx)
}

// Tick indicates an expected call of Tick.
func (mr *MockMatchmakingServiceMockRecorder) Tick(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tick", reflect.TypeOf((*MockMatchmakingService)(nil).Tick), ctx)
}

// MockConn is a mock of Conn interface.
type MockConn struct {
	ctrl     *gomock.Controller
	recorder *MockConnMockRecorder
	isgomock struct{}
}

// MockConnMockRecorder is the mock recorder for MockConn.
type MockConnMockRecorder struct {
	mock *MockConn
}

// NewMockConn creates a new mock instance.
func NewMockConn(ctrl *gomock.Controller) *MockConn {
	mock := &MockConn{ctrl: ctrl}
	mock.recorder = &MockConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConn) EXPECT() *MockConnMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConn) Close(reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", reason)
}

// Close indicates an expected call of Close.
func (mr *MockConnMockRecorder) Close(reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConn)(nil).Close), reason)
}

// Send mocks base method.
func (m *MockConn) Send(msg domain.MatchedMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockConnMockRecorder) Send(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockConn)(nil).Send), msg)
}

// UserID mocks base method.
func (m *MockConn) UserID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockConnMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockConn)(nil).UserID))
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}

// MockRoomIDGenerator is a mock of RoomIDGenerator interface.
type MockRoomIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRoomIDGeneratorMockRecorder
	isgomock struct{}
}

// MockRoomIDGeneratorMockRecorder is the mock recorder for MockRoomIDGenerator.
type MockRoomIDGeneratorMockRecorder struct {
	mock *MockRoomIDGenerator
}

// NewMockRoomIDGenerator creates a new mock instance.
func NewMockRoomIDGenerator(ctrl *gomock.Controller) *MockRoomIDGenerator {
	mock := &MockRoomIDGenerator{ctrl: ctrl}
	mock.recorder = &MockRoomIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomIDGenerator) EXPECT() *MockRoomIDGeneratorMockRecorder {
	return m.recorder
}

// NewRoomID mocks base method.
func (m *MockRoomIDGenerator) NewRoomID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRoomID")
	ret0, _ := ret[0].(string)
	return ret0
}

// NewRoomID indicates an expected call of NewRoomID.
func (mr *MockRoomIDGeneratorMockRecorder) NewRoomID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRoomID", reflect.TypeOf((*MockRoomIDGenerator)(nil).NewRoomID))
}
