// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/reports/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReportsService is a mock of ReportsService interface.
type MockReportsService struct {
	ctrl     *gomock.Controller
	recorder *MockReportsServiceMockRecorder
	isgomock struct{}
}

// MockReportsServiceMockRecorder is the mock recorder for MockReportsService.
type MockReportsServiceMockRecorder struct {
	mock *MockReportsService
}

// NewMockReportsService creates a new mock instance.
func NewMockReportsService(ctrl *gomock.Controller) *MockReportsService {
	mock := &MockReportsService{ctrl: ctrl}
	mock.recorder = &MockReportsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportsService) EXPECT() *MockReportsServiceMockRecorder {
	return m.recorder
}

// GetCooldown mocks base method.
func (m *MockReportsService) GetCooldown(ctx context.Context, userID int64) (domain.CooldownStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCooldown", ctx, userID)
	ret0, _ := ret[0].(domain.CooldownStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCooldown indicates an expected call of GetCooldown.
func (mr *MockReportsServiceMockRecorder) GetCooldown(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCooldown", reflect.TypeOf((*MockReportsService)(nil).GetCooldown), ctx, userID)
}

// ReportCheat mocks base method.
func (m *MockReportsService) ReportCheat(ctx context.Context, reporterID, reportedID int64, matchID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportCheat", ctx, reporterID, reportedID, matchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportCheat indicates an expected call of ReportCheat.
func (mr *MockReportsServiceMockRecorder) ReportCheat(ctx, reporterID, reportedID, matchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportCheat", reflect.TypeOf((*MockReportsService)(nil).ReportCheat), ctx, reporterID, reportedID, matchID)
}

// MockBugReportService is a mock of BugReportService interface.
type MockBugReportService struct {
	ctrl     *gomock.Controller
	recorder *MockBugReportServiceMockRecorder
	isgomock struct{}
}

// MockBugReportServiceMockRecorder is the mock recorder for MockBugReportService.
type MockBugReportServiceMockRecorder struct {
	mock *MockBugReportService
}

// NewMockBugReportService creates a new mock instance.
func NewMockBugReportService(ctrl *gomock.Controller) *MockBugReportService {
	mock := &MockBugReportService{ctrl: ctrl}
	mock.recorder = &MockBugReportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBugReportService) EXPECT() *MockBugReportServiceMockRecorder {
	return m.recorder
}

// ReportBug mocks base method.
func (m *MockBugReportService) ReportBug(ctx context.Context, userID int64, device, description string, recording []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportBug", ctx, userID, device, description, recording)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportBug indicates an expected call of ReportBug.
func (mr *MockBugReportServiceMockRecorder) ReportBug(ctx, userID, device, description, recording any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportBug", reflect.TypeOf((*MockBugReportService)(nil).ReportBug), ctx, userID, device, description, recording)
}

// MockSessionService is a mock of SessionService interface.
type MockSessionService struct {
	ctrl     *gomock.Controller
	recorder *MockSessionServiceMockRecorder
	isgomock struct{}
}

// MockSessionServiceMockRecorder is the mock recorder for MockSessionService.
type MockSessionServiceMockRecorder struct {
	mock *MockSessionService
}

// NewMockSessionService creates a new mock instance.
func NewMockSessionService(ctrl *gomock.Controller) *MockSessionService {
	mock := &MockSessionService{ctrl: ctrl}
	mock.recorder = &MockSessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionService) EXPECT() *MockSessionServiceMockRecorder {
	return m.recorder
}

// ResolveSession mocks base method.
func (m *MockSessionService) ResolveSession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSession indicates an expected call of ResolveSession.
func (mr *MockSessionServiceMockRecorder) ResolveSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSession", reflect.TypeOf((*MockSessionService)(nil).ResolveSession), ctx, sessionID)
}

// MockTelegramNotifier is a mock of TelegramNotifier interface.
type MockTelegramNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramNotifierMockRecorder
	isgomock struct{}
}

// MockTelegramNotifierMockRecorder is the mock recorder for MockTelegramNotifier.
type MockTelegramNotifierMockRecorder struct {
	mock *MockTelegramNotifier
}

// NewMockTelegramNotifier creates a new mock instance.
func NewMockTelegramNotifier(ctrl *gomock.Controller) *MockTelegramNotifier {
	mock := &MockTelegramNotifier{ctrl: ctrl}
	mock.recorder = &MockTelegramNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramNotifier) EXPECT() *MockTelegramNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockTelegramNotifier) Notify(ctx context.Context, userID int64, device, description, objectRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, userID, device, description, objectRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockTelegramNotifierMockRecorder) Notify(ctx, userID, device, description, objectRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockTelegramNotifier)(nil).Notify), ctx, userID, device, description, objectRef)
}
