// Code generated by MockGen. DO NOT EDIT.
// Source: /mnt/c/Users/user1337/work/staring-startup/reports-cheat-cooldown/services/reports/internal/api/service/service.go
//
// Generated by this command:
//
//	mockgen -source=/mnt/c/Users/user1337/work/staring-startup/reports-cheat-cooldown/services/reports/internal/api/service/service.go -destination=/mnt/c/Users/user1337/work/staring-startup/reports-cheat-cooldown/services/reports/internal/api/service/mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/reports/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReportsService is a mock of ReportsService interface.
type MockReportsService struct {
	ctrl     *gomock.Controller
	recorder *MockReportsServiceMockRecorder
	isgomock struct{}
}

// MockReportsServiceMockRecorder is the mock recorder for MockReportsService.
type MockReportsServiceMockRecorder struct {
	mock *MockReportsService
}

// NewMockReportsService creates a new mock instance.
func NewMockReportsService(ctrl *gomock.Controller) *MockReportsService {
	mock := &MockReportsService{ctrl: ctrl}
	mock.recorder = &MockReportsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportsService) EXPECT() *MockReportsServiceMockRecorder {
	return m.recorder
}

// GetCooldown mocks base method.
func (m *MockReportsService) GetCooldown(ctx context.Context, userID int64) (domain.CooldownStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCooldown", ctx, userID)
	ret0, _ := ret[0].(domain.CooldownStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCooldown indicates an expected call of GetCooldown.
func (mr *MockReportsServiceMockRecorder) GetCooldown(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCooldown", reflect.TypeOf((*MockReportsService)(nil).GetCooldown), ctx, userID)
}

// ReportCheat mocks base method.
func (m *MockReportsService) ReportCheat(ctx context.Context, reporterID, reportedID int64, matchID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportCheat", ctx, reporterID, reportedID, matchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReportCheat indicates an expected call of ReportCheat.
func (mr *MockReportsServiceMockRecorder) ReportCheat(ctx, reporterID, reportedID, matchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportCheat", reflect.TypeOf((*MockReportsService)(nil).ReportCheat), ctx, reporterID, reportedID, matchID)
}
