// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pizdagladki/full/services/reports/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCheatReportsRepository is a mock of CheatReportsRepository interface.
type MockCheatReportsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheatReportsRepositoryMockRecorder
	isgomock struct{}
}

// MockCheatReportsRepositoryMockRecorder is the mock recorder for MockCheatReportsRepository.
type MockCheatReportsRepositoryMockRecorder struct {
	mock *MockCheatReportsRepository
}

// NewMockCheatReportsRepository creates a new mock instance.
func NewMockCheatReportsRepository(ctrl *gomock.Controller) *MockCheatReportsRepository {
	mock := &MockCheatReportsRepository{ctrl: ctrl}
	mock.recorder = &MockCheatReportsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheatReportsRepository) EXPECT() *MockCheatReportsRepositoryMockRecorder {
	return m.recorder
}

// CountRecentCheatReports mocks base method.
func (m *MockCheatReportsRepository) CountRecentCheatReports(ctx context.Context, reportedID int64, lastNMatches int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentCheatReports", ctx, reportedID, lastNMatches)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentCheatReports indicates an expected call of CountRecentCheatReports.
func (mr *MockCheatReportsRepositoryMockRecorder) CountRecentCheatReports(ctx, reportedID, lastNMatches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentCheatReports", reflect.TypeOf((*MockCheatReportsRepository)(nil).CountRecentCheatReports), ctx, reportedID, lastNMatches)
}

// UpsertCheatReport mocks base method.
func (m *MockCheatReportsRepository) UpsertCheatReport(ctx context.Context, report domain.CheatReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCheatReport", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCheatReport indicates an expected call of UpsertCheatReport.
func (mr *MockCheatReportsRepositoryMockRecorder) UpsertCheatReport(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCheatReport", reflect.TypeOf((*MockCheatReportsRepository)(nil).UpsertCheatReport), ctx, report)
}

// MockCooldownStore is a mock of CooldownStore interface.
type MockCooldownStore struct {
	ctrl     *gomock.Controller
	recorder *MockCooldownStoreMockRecorder
	isgomock struct{}
}

// MockCooldownStoreMockRecorder is the mock recorder for MockCooldownStore.
type MockCooldownStoreMockRecorder struct {
	mock *MockCooldownStore
}

// NewMockCooldownStore creates a new mock instance.
func NewMockCooldownStore(ctrl *gomock.Controller) *MockCooldownStore {
	mock := &MockCooldownStore{ctrl: ctrl}
	mock.recorder = &MockCooldownStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCooldownStore) EXPECT() *MockCooldownStoreMockRecorder {
	return m.recorder
}

// GetCooldown mocks base method.
func (m *MockCooldownStore) GetCooldown(ctx context.Context, userID int64) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCooldown", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCooldown indicates an expected call of GetCooldown.
func (mr *MockCooldownStoreMockRecorder) GetCooldown(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCooldown", reflect.TypeOf((*MockCooldownStore)(nil).GetCooldown), ctx, userID)
}

// SetCooldown mocks base method.
func (m *MockCooldownStore) SetCooldown(ctx context.Context, userID int64, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCooldown", ctx, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCooldown indicates an expected call of SetCooldown.
func (mr *MockCooldownStoreMockRecorder) SetCooldown(ctx, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCooldown", reflect.TypeOf((*MockCooldownStore)(nil).SetCooldown), ctx, userID, ttl)
}

// MockBugReportsRepository is a mock of BugReportsRepository interface.
type MockBugReportsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBugReportsRepositoryMockRecorder
	isgomock struct{}
}

// MockBugReportsRepositoryMockRecorder is the mock recorder for MockBugReportsRepository.
type MockBugReportsRepositoryMockRecorder struct {
	mock *MockBugReportsRepository
}

// NewMockBugReportsRepository creates a new mock instance.
func NewMockBugReportsRepository(ctrl *gomock.Controller) *MockBugReportsRepository {
	mock := &MockBugReportsRepository{ctrl: ctrl}
	mock.recorder = &MockBugReportsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBugReportsRepository) EXPECT() *MockBugReportsRepositoryMockRecorder {
	return m.recorder
}

// InsertBugReport mocks base method.
func (m *MockBugReportsRepository) InsertBugReport(ctx context.Context, report domain.BugReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertBugReport", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertBugReport indicates an expected call of InsertBugReport.
func (mr *MockBugReportsRepositoryMockRecorder) InsertBugReport(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertBugReport", reflect.TypeOf((*MockBugReportsRepository)(nil).InsertBugReport), ctx, report)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// UserIDBySession mocks base method.
func (m *MockSessionRepository) UserIDBySession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDBySession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIDBySession indicates an expected call of UserIDBySession.
func (mr *MockSessionRepositoryMockRecorder) UserIDBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDBySession", reflect.TypeOf((*MockSessionRepository)(nil).UserIDBySession), ctx, sessionID)
}

// MockBugRecordingStorage is a mock of BugRecordingStorage interface.
type MockBugRecordingStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBugRecordingStorageMockRecorder
	isgomock struct{}
}

// MockBugRecordingStorageMockRecorder is the mock recorder for MockBugRecordingStorage.
type MockBugRecordingStorageMockRecorder struct {
	mock *MockBugRecordingStorage
}

// NewMockBugRecordingStorage creates a new mock instance.
func NewMockBugRecordingStorage(ctrl *gomock.Controller) *MockBugRecordingStorage {
	mock := &MockBugRecordingStorage{ctrl: ctrl}
	mock.recorder = &MockBugRecordingStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBugRecordingStorage) EXPECT() *MockBugRecordingStorageMockRecorder {
	return m.recorder
}

// StoreRecording mocks base method.
func (m *MockBugRecordingStorage) StoreRecording(ctx context.Context, key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRecording", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRecording indicates an expected call of StoreRecording.
func (mr *MockBugRecordingStorageMockRecorder) StoreRecording(ctx, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRecording", reflect.TypeOf((*MockBugRecordingStorage)(nil).StoreRecording), ctx, key, data)
}
