// Code generated by MockGen. DO NOT EDIT.
// Source: /mnt/c/Users/user1337/work/staring-startup/reports-cheat-cooldown/services/reports/internal/api/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pizdagladki/full/services/reports/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCheatReportsRepository is a mock of CheatReportsRepository interface.
type MockCheatReportsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCheatReportsRepositoryMockRecorder
	isgomock struct{}
}

// MockCheatReportsRepositoryMockRecorder is the mock recorder for MockCheatReportsRepository.
type MockCheatReportsRepositoryMockRecorder struct {
	mock *MockCheatReportsRepository
}

// NewMockCheatReportsRepository creates a new mock instance.
func NewMockCheatReportsRepository(ctrl *gomock.Controller) *MockCheatReportsRepository {
	mock := &MockCheatReportsRepository{ctrl: ctrl}
	mock.recorder = &MockCheatReportsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheatReportsRepository) EXPECT() *MockCheatReportsRepositoryMockRecorder {
	return m.recorder
}

// CountRecentCheatReports mocks base method.
func (m *MockCheatReportsRepository) CountRecentCheatReports(ctx context.Context, reportedID int64, lastNMatches int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRecentCheatReports", ctx, reportedID, lastNMatches)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRecentCheatReports indicates an expected call of CountRecentCheatReports.
func (mr *MockCheatReportsRepositoryMockRecorder) CountRecentCheatReports(ctx, reportedID, lastNMatches any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRecentCheatReports", reflect.TypeOf((*MockCheatReportsRepository)(nil).CountRecentCheatReports), ctx, reportedID, lastNMatches)
}

// UpsertCheatReport mocks base method.
func (m *MockCheatReportsRepository) UpsertCheatReport(ctx context.Context, report domain.CheatReport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertCheatReport", ctx, report)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertCheatReport indicates an expected call of UpsertCheatReport.
func (mr *MockCheatReportsRepositoryMockRecorder) UpsertCheatReport(ctx, report any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertCheatReport", reflect.TypeOf((*MockCheatReportsRepository)(nil).UpsertCheatReport), ctx, report)
}

// MockCooldownStore is a mock of CooldownStore interface.
type MockCooldownStore struct {
	ctrl     *gomock.Controller
	recorder *MockCooldownStoreMockRecorder
	isgomock struct{}
}

// MockCooldownStoreMockRecorder is the mock recorder for MockCooldownStore.
type MockCooldownStoreMockRecorder struct {
	mock *MockCooldownStore
}

// NewMockCooldownStore creates a new mock instance.
func NewMockCooldownStore(ctrl *gomock.Controller) *MockCooldownStore {
	mock := &MockCooldownStore{ctrl: ctrl}
	mock.recorder = &MockCooldownStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCooldownStore) EXPECT() *MockCooldownStoreMockRecorder {
	return m.recorder
}

// GetCooldown mocks base method.
func (m *MockCooldownStore) GetCooldown(ctx context.Context, userID int64) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCooldown", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCooldown indicates an expected call of GetCooldown.
func (mr *MockCooldownStoreMockRecorder) GetCooldown(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCooldown", reflect.TypeOf((*MockCooldownStore)(nil).GetCooldown), ctx, userID)
}

// SetCooldown mocks base method.
func (m *MockCooldownStore) SetCooldown(ctx context.Context, userID int64, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCooldown", ctx, userID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCooldown indicates an expected call of SetCooldown.
func (mr *MockCooldownStoreMockRecorder) SetCooldown(ctx, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCooldown", reflect.TypeOf((*MockCooldownStore)(nil).SetCooldown), ctx, userID, ttl)
}
