// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/media/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClipRepository is a mock of ClipRepository interface.
type MockClipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClipRepositoryMockRecorder
	isgomock struct{}
}

// MockClipRepositoryMockRecorder is the mock recorder for MockClipRepository.
type MockClipRepositoryMockRecorder struct {
	mock *MockClipRepository
}

// NewMockClipRepository creates a new mock instance.
func NewMockClipRepository(ctrl *gomock.Controller) *MockClipRepository {
	mock := &MockClipRepository{ctrl: ctrl}
	mock.recorder = &MockClipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClipRepository) EXPECT() *MockClipRepositoryMockRecorder {
	return m.recorder
}

// ClaimConversion mocks base method.
func (m *MockClipRepository) ClaimConversion(ctx context.Context, id int64, mp4Key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimConversion", ctx, id, mp4Key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimConversion indicates an expected call of ClaimConversion.
func (mr *MockClipRepositoryMockRecorder) ClaimConversion(ctx, id, mp4Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimConversion", reflect.TypeOf((*MockClipRepository)(nil).ClaimConversion), ctx, id, mp4Key)
}

// Create mocks base method.
func (m *MockClipRepository) Create(ctx context.Context, clip domain.Clip) (domain.Clip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clip)
	ret0, _ := ret[0].(domain.Clip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClipRepositoryMockRecorder) Create(ctx, clip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClipRepository)(nil).Create), ctx, clip)
}

// DeleteOldestBeyondLimit mocks base method.
func (m *MockClipRepository) DeleteOldestBeyondLimit(ctx context.Context, userID int64, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldestBeyondLimit", ctx, userID, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOldestBeyondLimit indicates an expected call of DeleteOldestBeyondLimit.
func (mr *MockClipRepositoryMockRecorder) DeleteOldestBeyondLimit(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldestBeyondLimit", reflect.TypeOf((*MockClipRepository)(nil).DeleteOldestBeyondLimit), ctx, userID, limit)
}

// GetByID mocks base method.
func (m *MockClipRepository) GetByID(ctx context.Context, id int64) (domain.Clip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Clip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClipRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClipRepository)(nil).GetByID), ctx, id)
}

// ListByUser mocks base method.
func (m *MockClipRepository) ListByUser(ctx context.Context, userID int64) ([]domain.Clip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.Clip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockClipRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockClipRepository)(nil).ListByUser), ctx, userID)
}

// UpdateConversion mocks base method.
func (m *MockClipRepository) UpdateConversion(ctx context.Context, id int64, mp4Key, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConversion", ctx, id, mp4Key, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateConversion indicates an expected call of UpdateConversion.
func (mr *MockClipRepositoryMockRecorder) UpdateConversion(ctx, id, mp4Key, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConversion", reflect.TypeOf((*MockClipRepository)(nil).UpdateConversion), ctx, id, mp4Key, status)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// UserIDBySession mocks base method.
func (m *MockSessionRepository) UserIDBySession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDBySession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIDBySession indicates an expected call of UserIDBySession.
func (mr *MockSessionRepositoryMockRecorder) UserIDBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDBySession", reflect.TypeOf((*MockSessionRepository)(nil).UserIDBySession), ctx, sessionID)
}

// MockKingClipRepository is a mock of KingClipRepository interface.
type MockKingClipRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKingClipRepositoryMockRecorder
	isgomock struct{}
}

// MockKingClipRepositoryMockRecorder is the mock recorder for MockKingClipRepository.
type MockKingClipRepositoryMockRecorder struct {
	mock *MockKingClipRepository
}

// NewMockKingClipRepository creates a new mock instance.
func NewMockKingClipRepository(ctrl *gomock.Controller) *MockKingClipRepository {
	mock := &MockKingClipRepository{ctrl: ctrl}
	mock.recorder = &MockKingClipRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKingClipRepository) EXPECT() *MockKingClipRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockKingClipRepository) Create(ctx context.Context, clip domain.KingClip) (domain.KingClip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clip)
	ret0, _ := ret[0].(domain.KingClip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockKingClipRepositoryMockRecorder) Create(ctx, clip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockKingClipRepository)(nil).Create), ctx, clip)
}

// Delete mocks base method.
func (m *MockKingClipRepository) Delete(ctx context.Context, id int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockKingClipRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKingClipRepository)(nil).Delete), ctx, id)
}

// DeleteExpired mocks base method.
func (m *MockKingClipRepository) DeleteExpired(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockKingClipRepositoryMockRecorder) DeleteExpired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockKingClipRepository)(nil).DeleteExpired), ctx)
}

// DeleteSupersededByHill mocks base method.
func (m *MockKingClipRepository) DeleteSupersededByHill(ctx context.Context, hillType string, keepID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupersededByHill", ctx, hillType, keepID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSupersededByHill indicates an expected call of DeleteSupersededByHill.
func (mr *MockKingClipRepositoryMockRecorder) DeleteSupersededByHill(ctx, hillType, keepID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupersededByHill", reflect.TypeOf((*MockKingClipRepository)(nil).DeleteSupersededByHill), ctx, hillType, keepID)
}

// GetByID mocks base method.
func (m *MockKingClipRepository) GetByID(ctx context.Context, id int64) (domain.KingClip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.KingClip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockKingClipRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockKingClipRepository)(nil).GetByID), ctx, id)
}

// GetCurrent mocks base method.
func (m *MockKingClipRepository) GetCurrent(ctx context.Context, hillType string) (domain.KingClip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrent", ctx, hillType)
	ret0, _ := ret[0].(domain.KingClip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrent indicates an expected call of GetCurrent.
func (mr *MockKingClipRepositoryMockRecorder) GetCurrent(ctx, hillType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrent", reflect.TypeOf((*MockKingClipRepository)(nil).GetCurrent), ctx, hillType)
}
