// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/store/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogRepository is a mock of CatalogRepository interface.
type MockCatalogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogRepositoryMockRecorder
	isgomock struct{}
}

// MockCatalogRepositoryMockRecorder is the mock recorder for MockCatalogRepository.
type MockCatalogRepositoryMockRecorder struct {
	mock *MockCatalogRepository
}

// NewMockCatalogRepository creates a new mock instance.
func NewMockCatalogRepository(ctrl *gomock.Controller) *MockCatalogRepository {
	mock := &MockCatalogRepository{ctrl: ctrl}
	mock.recorder = &MockCatalogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogRepository) EXPECT() *MockCatalogRepositoryMockRecorder {
	return m.recorder
}

// ListProducts mocks base method.
func (m *MockCatalogRepository) ListProducts(ctx context.Context, kind *string) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, kind)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockCatalogRepositoryMockRecorder) ListProducts(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockCatalogRepository)(nil).ListProducts), ctx, kind)
}

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockInventoryRepository) ListByUser(ctx context.Context, userID int64) ([]domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockInventoryRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockInventoryRepository)(nil).ListByUser), ctx, userID)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// UserIDBySession mocks base method.
func (m *MockSessionRepository) UserIDBySession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDBySession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIDBySession indicates an expected call of UserIDBySession.
func (mr *MockSessionRepositoryMockRecorder) UserIDBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDBySession", reflect.TypeOf((*MockSessionRepository)(nil).UserIDBySession), ctx, sessionID)
}
