// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/pizdagladki/full/services/store/internal/api/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPurchaseRepository is a mock of PurchaseRepository interface.
type MockPurchaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseRepositoryMockRecorder
	isgomock struct{}
}

// MockPurchaseRepositoryMockRecorder is the mock recorder for MockPurchaseRepository.
type MockPurchaseRepositoryMockRecorder struct {
	mock *MockPurchaseRepository
}

// NewMockPurchaseRepository creates a new mock instance.
func NewMockPurchaseRepository(ctrl *gomock.Controller) *MockPurchaseRepository {
	mock := &MockPurchaseRepository{ctrl: ctrl}
	mock.recorder = &MockPurchaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseRepository) EXPECT() *MockPurchaseRepositoryMockRecorder {
	return m.recorder
}

// ConfirmAndGrant mocks base method.
func (m *MockPurchaseRepository) ConfirmAndGrant(ctx context.Context, providerRef, eventID, kind string, userID, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmAndGrant", ctx, providerRef, eventID, kind, userID, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmAndGrant indicates an expected call of ConfirmAndGrant.
func (mr *MockPurchaseRepositoryMockRecorder) ConfirmAndGrant(ctx, providerRef, eventID, kind, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmAndGrant", reflect.TypeOf((*MockPurchaseRepository)(nil).ConfirmAndGrant), ctx, providerRef, eventID, kind, userID, productID)
}

// CreatePurchase mocks base method.
func (m *MockPurchaseRepository) CreatePurchase(ctx context.Context, p domain.Purchase) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", ctx, p)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockPurchaseRepositoryMockRecorder) CreatePurchase(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockPurchaseRepository)(nil).CreatePurchase), ctx, p)
}

// FindByProviderRef mocks base method.
func (m *MockPurchaseRepository) FindByProviderRef(ctx context.Context, providerRef string) (*domain.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProviderRef", ctx, providerRef)
	ret0, _ := ret[0].(*domain.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProviderRef indicates an expected call of FindByProviderRef.
func (mr *MockPurchaseRepositoryMockRecorder) FindByProviderRef(ctx, providerRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProviderRef", reflect.TypeOf((*MockPurchaseRepository)(nil).FindByProviderRef), ctx, providerRef)
}

// GetProduct mocks base method.
func (m *MockPurchaseRepository) GetProduct(ctx context.Context, productID int64) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, productID)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockPurchaseRepositoryMockRecorder) GetProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockPurchaseRepository)(nil).GetProduct), ctx, productID)
}

// IsOwned mocks base method.
func (m *MockPurchaseRepository) IsOwned(ctx context.Context, userID, productID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOwned", ctx, userID, productID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOwned indicates an expected call of IsOwned.
func (mr *MockPurchaseRepositoryMockRecorder) IsOwned(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOwned", reflect.TypeOf((*MockPurchaseRepository)(nil).IsOwned), ctx, userID, productID)
}

// PurchaseWithPoints mocks base method.
func (m *MockPurchaseRepository) PurchaseWithPoints(ctx context.Context, userID, productID, pointsPrice int64, kind string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurchaseWithPoints", ctx, userID, productID, pointsPrice, kind)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurchaseWithPoints indicates an expected call of PurchaseWithPoints.
func (mr *MockPurchaseRepositoryMockRecorder) PurchaseWithPoints(ctx, userID, productID, pointsPrice, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurchaseWithPoints", reflect.TypeOf((*MockPurchaseRepository)(nil).PurchaseWithPoints), ctx, userID, productID, pointsPrice, kind)
}

// WebhookEventExists mocks base method.
func (m *MockPurchaseRepository) WebhookEventExists(ctx context.Context, eventID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WebhookEventExists", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WebhookEventExists indicates an expected call of WebhookEventExists.
func (mr *MockPurchaseRepositoryMockRecorder) WebhookEventExists(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WebhookEventExists", reflect.TypeOf((*MockPurchaseRepository)(nil).WebhookEventExists), ctx, eventID)
}

// MockCatalogRepository is a mock of CatalogRepository interface.
type MockCatalogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogRepositoryMockRecorder
	isgomock struct{}
}

// MockCatalogRepositoryMockRecorder is the mock recorder for MockCatalogRepository.
type MockCatalogRepositoryMockRecorder struct {
	mock *MockCatalogRepository
}

// NewMockCatalogRepository creates a new mock instance.
func NewMockCatalogRepository(ctrl *gomock.Controller) *MockCatalogRepository {
	mock := &MockCatalogRepository{ctrl: ctrl}
	mock.recorder = &MockCatalogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogRepository) EXPECT() *MockCatalogRepositoryMockRecorder {
	return m.recorder
}

// ListProducts mocks base method.
func (m *MockCatalogRepository) ListProducts(ctx context.Context, kind *string) ([]domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, kind)
	ret0, _ := ret[0].([]domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockCatalogRepositoryMockRecorder) ListProducts(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockCatalogRepository)(nil).ListProducts), ctx, kind)
}

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockInventoryRepository) ListByUser(ctx context.Context, userID int64) ([]domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockInventoryRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockInventoryRepository)(nil).ListByUser), ctx, userID)
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// UserIDBySession mocks base method.
func (m *MockSessionRepository) UserIDBySession(ctx context.Context, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIDBySession", ctx, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIDBySession indicates an expected call of UserIDBySession.
func (mr *MockSessionRepositoryMockRecorder) UserIDBySession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIDBySession", reflect.TypeOf((*MockSessionRepository)(nil).UserIDBySession), ctx, sessionID)
}

// MockPointsRepository is a mock of PointsRepository interface.
type MockPointsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPointsRepositoryMockRecorder
	isgomock struct{}
}

// MockPointsRepositoryMockRecorder is the mock recorder for MockPointsRepository.
type MockPointsRepositoryMockRecorder struct {
	mock *MockPointsRepository
}

// NewMockPointsRepository creates a new mock instance.
func NewMockPointsRepository(ctrl *gomock.Controller) *MockPointsRepository {
	mock := &MockPointsRepository{ctrl: ctrl}
	mock.recorder = &MockPointsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPointsRepository) EXPECT() *MockPointsRepositoryMockRecorder {
	return m.recorder
}

// Credit mocks base method.
func (m *MockPointsRepository) Credit(ctx context.Context, userID, delta int64, reason, refID string) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credit", ctx, userID, delta, reason, refID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Credit indicates an expected call of Credit.
func (mr *MockPointsRepositoryMockRecorder) Credit(ctx, userID, delta, reason, refID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credit", reflect.TypeOf((*MockPointsRepository)(nil).Credit), ctx, userID, delta, reason, refID)
}

// GetBalance mocks base method.
func (m *MockPointsRepository) GetBalance(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockPointsRepositoryMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockPointsRepository)(nil).GetBalance), ctx, userID)
}

// MockPointsCache is a mock of PointsCache interface.
type MockPointsCache struct {
	ctrl     *gomock.Controller
	recorder *MockPointsCacheMockRecorder
	isgomock struct{}
}

// MockPointsCacheMockRecorder is the mock recorder for MockPointsCache.
type MockPointsCacheMockRecorder struct {
	mock *MockPointsCache
}

// NewMockPointsCache creates a new mock instance.
func NewMockPointsCache(ctrl *gomock.Controller) *MockPointsCache {
	mock := &MockPointsCache{ctrl: ctrl}
	mock.recorder = &MockPointsCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPointsCache) EXPECT() *MockPointsCacheMockRecorder {
	return m.recorder
}

// DeleteBalance mocks base method.
func (m *MockPointsCache) DeleteBalance(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBalance", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBalance indicates an expected call of DeleteBalance.
func (mr *MockPointsCacheMockRecorder) DeleteBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBalance", reflect.TypeOf((*MockPointsCache)(nil).DeleteBalance), ctx, userID)
}

// GetBalance mocks base method.
func (m *MockPointsCache) GetBalance(ctx context.Context, userID int64) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockPointsCacheMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockPointsCache)(nil).GetBalance), ctx, userID)
}

// SetBalance mocks base method.
func (m *MockPointsCache) SetBalance(ctx context.Context, userID, balance int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBalance", ctx, userID, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBalance indicates an expected call of SetBalance.
func (mr *MockPointsCacheMockRecorder) SetBalance(ctx, userID, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBalance", reflect.TypeOf((*MockPointsCache)(nil).SetBalance), ctx, userID, balance)
}

// MockRewardedRepository is a mock of RewardedRepository interface.
type MockRewardedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRewardedRepositoryMockRecorder
	isgomock struct{}
}

// MockRewardedRepositoryMockRecorder is the mock recorder for MockRewardedRepository.
type MockRewardedRepositoryMockRecorder struct {
	mock *MockRewardedRepository
}

// NewMockRewardedRepository creates a new mock instance.
func NewMockRewardedRepository(ctrl *gomock.Controller) *MockRewardedRepository {
	mock := &MockRewardedRepository{ctrl: ctrl}
	mock.recorder = &MockRewardedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardedRepository) EXPECT() *MockRewardedRepositoryMockRecorder {
	return m.recorder
}

// GetProduct mocks base method.
func (m *MockRewardedRepository) GetProduct(ctx context.Context, productID int64) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, productID)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockRewardedRepositoryMockRecorder) GetProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockRewardedRepository)(nil).GetProduct), ctx, productID)
}

// GrantFreeDistraction mocks base method.
func (m *MockRewardedRepository) GrantFreeDistraction(ctx context.Context, userID, productID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantFreeDistraction", ctx, userID, productID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GrantFreeDistraction indicates an expected call of GrantFreeDistraction.
func (mr *MockRewardedRepositoryMockRecorder) GrantFreeDistraction(ctx, userID, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantFreeDistraction", reflect.TypeOf((*MockRewardedRepository)(nil).GrantFreeDistraction), ctx, userID, productID)
}

// MockRewardedRateLimiter is a mock of RewardedRateLimiter interface.
type MockRewardedRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockRewardedRateLimiterMockRecorder
	isgomock struct{}
}

// MockRewardedRateLimiterMockRecorder is the mock recorder for MockRewardedRateLimiter.
type MockRewardedRateLimiterMockRecorder struct {
	mock *MockRewardedRateLimiter
}

// NewMockRewardedRateLimiter creates a new mock instance.
func NewMockRewardedRateLimiter(ctrl *gomock.Controller) *MockRewardedRateLimiter {
	mock := &MockRewardedRateLimiter{ctrl: ctrl}
	mock.recorder = &MockRewardedRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRewardedRateLimiter) EXPECT() *MockRewardedRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockRewardedRateLimiter) Allow(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockRewardedRateLimiterMockRecorder) Allow(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockRewardedRateLimiter)(nil).Allow), ctx, userID)
}
